### ISSUE TITLE
invalid syntax line 32 of room.py

### ISSUE THREAD

**Issue by ggarin** [ThT12/TextAdventure#2]
![](https://media.giphy.com/media/80TEu4wOBdPLG/giphy.gif)

**Comment by ThT12** [comment]
Impossible de réitérer le bug chez moi. La ligne est question peu être considérée comme peu commune (niveau syntaxique) et n'est peu être pas supportée par toute les versions de python.

Tu utilise quoi comme version ?

Merci !

**Comment by ThT12** [comment]
Si tu as l'occas' test la nouvelle version qui devrait être plus générique !
Merci
